kind = "web"
previewPath = "/"
title = "Abajiraf Restaurant Management"
version = "1.0.0"
id = "rHbsh9KuLn3RsTmYvDj5"

[[services]]
localPort = 3000
name = "web"
paths = ["/"]

[services.env]
PORT = "3000"

[services.development]
run = "pnpm --filter @workspace/nextjs-app run dev"
